# Generic

generic:
  continue:    'Continue'
  resume:      'Resume'
  launch:      'Launch your shop!'
  setShutDown: 'Skip this tutorial'
  stop:        'Stop the OnBoarding'

# Content Welcome

welcome:
  text:   'Welcome to your shop, we will help you to create your first product, this will be awesome!'
  button: 'Start'

end:
  text:   'All is done! Thank you for working with us!'
  button: 'Finished'

lost:
  lost:            'Hey! Are you lost?'
  continue:        'To continue, press this button:'
  definitly:       'If you want to definitly stop the OnBoarding, press this button:'
  definitlyButton: 'Definitly stop the onboarding'

# Steps

group1:
  title: 'Welcome'

  step1:
    title: 'Hello from the PrestaShop team !'

group2:
  title: 'Product creation'

  step1:
    title: 'Set the name of the product'
    text:  'Enter here the name of your new product'

  step2:
    title: 'Set the description of the product'
    text:  'Explain here how awesome is your product'

  step3:
    title: 'Everything has a price'
    text: 'Enter here the price of your product'

  step4:
    title: 'And some other options'
    text:  'Here you can fin other options'

  step5:
    title: 'All is done …'
    text:  'Now we will save your product and go to the products list'

  step6:
    title: 'Finished'
    text:  'Here is your new product! Wonderfull!'

  step7:
    title: 'Finished'
    text:  'ALL IS DONE!'

