# Generic

generic:
  continue:    'Continue'
  resume:      'Resume'
  launch:      'Launch your shop!'
  setShutDown: 'Skip this tutorial'
  stop:        'Stop the OnBoarding'

# Content Welcome

welcome:
  text:   'Welcome to your shop, we will help you to create your first product, this will be awesome!'
  button: 'Start'

end:
  text:   'All is done! Thank you for working with us!'
  button: 'Finished'

lost:
  lost:            'Hey! Are you lost?'
  continue:        'To continue, press this button:'
  definitly:       'If you want to definitly stop the OnBoarding, press this button:'
  definitlyButton: 'Definitly stop the onboarding'

# Steps

group1:
  title: TODO

  step1:
    title: TODO

group2:
  title: Let's create your first product

  step1:
    title: TODO
    text:  Give your product a catchy name

  step2:
    title: TODO
    text:  Fill in the essential details in this tab. The other tabs are for more advanced information.

  step3:
    title: TODO
    text: Add one or more pictures so your product looks tempting!

  step4:
    title: TODO
    text: How much do you want to sell it?

  step5:
    title: TODO
    text: Yay! You just created your first product. Looks good, right?

group3:
  title: Give your shop its own identity

  step1:
    title: TODO
    text: Here, you can customize the current theme for your shop.

  step2:
    title: TODO
    text: And a good way to start is to add your own logo here!
